---
title: "Introduction to Shiny"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(rpart)
library(rattle)
data('iris')
```

Sidebar {.sidebar}
==========================
```{r}
sliderInput(inputId = 'ncluster', label = 'Choose number of clusters',
            min=0, max=15, value=4)
selectInput(inputId='choose_features', label='Select input filters',
            choices = c(colnames(iris %>% select(-Species))), multiple = T)
```

Clustering
=========================================

Column
-----------------------------------

### No. of species per cluster
```{r}
renderPlot({
  model = kmeans(iris%>% select(-Species), input$ncluster)
  barplot(table(model$cluster), col = 'steelblue')
})
```

### Summary

```{r}
renderTable({
  model_cluster = kmeans(iris%>% select(-Species), input$ncluster)
  iris$cluster = model_cluster$cluster
  df_iris = as.data.frame(iris)
  df_iris %>% group_by(cluster) %>% 
    summarise(Avg_Sepal_Width=mean(Sepal.Width, na.rm=T),
              Avg_Sepal_Length = mean(Sepal.Length, na.rm=T),
              Avg_Petal_Width=mean(Petal.Width, na.rm=T),
              Avg_Petal_Length=mean(Petal.Length, na.rm=T))
})
```

Decision Trees
====================================

Column
----------------------------

### Tree Diagram
```{r}
renderPlot({
  iris_subset = iris[, c(input$choose_features, 'Species')]
  model_dt = rpart(Species~., data=iris_subset)
  fancyRpartPlot(model_dt)
})
```


