---
title: "Twitter Analysis"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(tm)
library(plotly)
library(wordcloud)
tweets = read.csv('e:/datasets/narendramodi_tweets.csv')
tweets$created_at = as.Date(tweets$created_at, '%Y-%m-%d')
tweets$year_month = format(tweets$created_at, '%Y-%m')
```

Sidebar {.sidebar}
----------------------------------------
```{r}
selectInput(inputId = 'select_period', label="Select Month",
            choices = unique(tweets$year_month), multiple = T)
sliderInput(inputId='min_freq', label='Select Minimum Frequency', min=1, max=100, value=5)
```


Row
-----------------------------

### Total Tweets
```{r}
valueBox(nrow(tweets), icon='fa fa-twitter')
```

### Average Likes
```{r}
avg_likes = mean(tweets$favorite_count, na.rm=T)
color_hex = ifelse(avg_likes>2000, '#c7e9b4', 'red')
valueBox(round(avg_likes,1), icon='fa fa-heart')
```

### Average Retweets
```{r}
avg_retweets = mean(tweets$retweets_count, na.rm=T)
valueBox(round(avg_retweets,1), icon='fa fa-retweet')
```

Row
---------------------------------
### Trending of Tweets
```{r}

renderPlot({
  line_chart = tweets %>% filter(year_month %in% input$select_period) %>% group_by(year_month) %>% summarise(count=n()) %>% ggplot(aes(x=year_month, y=count))+ geom_line(group=1, col='steelblue')
  ggplotly(line_chart)
}) 
```


Row
----------------------------------
### Most repeated words
```{r}
renderPlot({
  
  tweets$text = tolower(tweets$text)
  tweets$text = gsub('[^a-zA-Z0-9#& ]', '', tweets$text)
  tweets_subset = tweets %>% filter(year_month %in% input$select_period)
  row_words = strsplit(tweets_subset$text, split = ' ')
  words = unlist(row_words)
  words_freq = table(words)
  words_freq = as.data.frame(words_freq)
  stop_words = stopwords()
  
  words_freq = words_freq %>% filter(!words %in% stop_words)
  custom_words = c('amp;', 'rt')
  words_freq = words_freq %>% filter(!words %in% custom_words)
  wordcloud(words_freq$words,
            words_freq$Freq,
            min.freq = input$min_freq,
            colors = brewer.pal(8, "Dark2"),
            random.color = T,
            scale = c(10,1)
            )  
})


```

### Device-wise tweets
```{r}
renderPlot({
  bar_chart = tweets %>%  filter(year_month %in% input$select_period) %>% group_by(source) %>% summarise(count=n()) %>% ggplot(aes(x=source, y=count))+geom_bar(stat = 'identity', fill='steelblue')
  ggplotly(bar_chart)  
})

```

